version: "3.8"

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
    - ./:/app
    depends_on:
      - php-fpm
    ports:
    - '8080:80'

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
    - ./:/app
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "54321:5432"

volumes:
  postgres: